package com.panjx.clouddrive.core.ui

import com.panjx.clouddrive.core.modle.File

object FilePreviewParameterData {

    val FILE= File(
        id = 1006,
        userId = 12,
        fileId = 0,
        fileSHA256 = null,
        fileName = "个人资料",
        fileExtension = null,
        fileCategory = null,
        fileSize = null,
        filePid = 0,
        folderType = 1,
        deleteFlag = 2,
        recoveryTime = 0,
        createTime = 1687650050,
        lastUpdateTime = 0
    )

    val FILES = listOf(
        // 文件夹
        File(
            id = 1006,
            userId = 12,
            fileId = 0,
            fileSHA256 = null,
            fileName = "个人资料",
            fileExtension = null,
            fileCategory = null,
            fileSize = null,
            filePid = 0,
            folderType = 1,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650050,
            lastUpdateTime = 0
        ),
        File(
            id = 1002,
            userId = 12,
            fileId = 0,
            fileSHA256 = null,
            fileName = "图片素材",
            fileExtension = null,
            fileCategory = null,
            fileSize = null,
            filePid = 0,
            folderType = 1,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650010,
            lastUpdateTime = 0
        ),
        File(
            id = 1005,
            userId = 12,
            fileId = 0,
            fileSHA256 = null,
            fileName = "工作项目",
            fileExtension = null,
            fileCategory = null,
            fileSize = null,
            filePid = 0,
            folderType = 1,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650040,
            lastUpdateTime = 0
        ),
        File(
            id = 1001,
            userId = 12,
            fileId = 0,
            fileSHA256 = null,
            fileName = "我的文档",
            fileExtension = null,
            fileCategory = null,
            fileSize = null,
            filePid = 0,
            folderType = 1,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650000,
            lastUpdateTime = 0
        ),
        File(
            id = 1003,
            userId = 12,
            fileId = 0,
            fileSHA256 = null,
            fileName = "视频资料",
            fileExtension = null,
            fileCategory = null,
            fileSize = null,
            filePid = 0,
            folderType = 1,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650020,
            lastUpdateTime = 0
        ),
        File(
            id = 1004,
            userId = 12,
            fileId = 0,
            fileSHA256 = null,
            fileName = "音乐收藏",
            fileExtension = null,
            fileCategory = null,
            fileSize = null,
            filePid = 0,
            folderType = 1,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650030,
            lastUpdateTime = 0
        ),

        // 文件
        File(
            id = 1008,
            userId = 12,
            fileId = 102,
            fileSHA256 = "bbbb2222cccc3333dddd4444eeee5555ffff6666gggg7777",
            fileName = "个人简历",
            fileExtension = "pdf",
            fileCategory = "application/pdf",
            fileSize = "8388608",
            filePid = 0,
            folderType = 0,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650110,
            lastUpdateTime = 0
        ),
        File(
            id = 1009,
            userId = 12,
            fileId = 103,
            fileSHA256 = "cccc3333dddd4444eeee5555ffff6666gggg7777hhhh8888",
            fileName = "会议记录",
            fileExtension = "docx",
            fileCategory = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            fileSize = "4194304",
            filePid = 0,
            folderType = 0,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650120,
            lastUpdateTime = 0
        ),
        File(
            id = 1018,
            userId = 12,
            fileId = 112,
            fileSHA256 = "llll2222mmmm3333nnnn4444oooo5555pppp6666qqqq7777",
            fileName = "公司标志",
            fileExtension = "png",
            fileCategory = "image/png",
            fileSize = "8192",
            filePid = 0,
            folderType = 0,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650210,
            lastUpdateTime = 0
        ),
        File(
            id = 1016,
            userId = 12,
            fileId = 110,
            fileSHA256 = "jjjj0000kkkk1111llll2222mmmm3333nnnn4444oooo5555",
            fileName = "团队宣传片",
            fileExtension = "mp4",
            fileCategory = "video/mp4",
            fileSize = "32768",
            filePid = 0,
            folderType = 0,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650190,
            lastUpdateTime = 0
        ),
        File(
            id = 1012,
            userId = 12,
            fileId = 106,
            fileSHA256 = "ffff6666gggg7777hhhh8888iiii9999jjjj0000kkkk1111",
            fileName = "家庭照片",
            fileExtension = "jpg",
            fileCategory = "image/jpeg",
            fileSize = "524288",
            filePid = 0,
            folderType = 0,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650150,
            lastUpdateTime = 0
        ),
        File(
            id = 1007,
            userId = 12,
            fileId = 101,
            fileSHA256 = "aaaa1111bbbb2222cccc3333dddd4444eeee5555ffff6666",
            fileName = "年度计划",
            fileExtension = "xlsx",
            fileCategory = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            fileSize = "12582912",
            filePid = 0,
            folderType = 0,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650100,
            lastUpdateTime = 0
        ),
        File(
            id = 1017,
            userId = 12,
            fileId = 111,
            fileSHA256 = "kkkk1111llll2222mmmm3333nnnn4444oooo5555pppp6666",
            fileName = "放松音乐",
            fileExtension = "mp3",
            fileCategory = "audio/mpeg",
            fileSize = "16384",
            filePid = 0,
            folderType = 0,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650200,
            lastUpdateTime = 0
        ),
        File(
            id = 1011,
            userId = 12,
            fileId = 105,
            fileSHA256 = "eeee5555ffff6666gggg7777hhhh8888iiii9999jjjj0000",
            fileName = "新年祝福视频",
            fileExtension = "mp4",
            fileCategory = "video/mp4",
            fileSize = "1048576",
            filePid = 0,
            folderType = 0,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650140,
            lastUpdateTime = 0
        ),
        File(
            id = 1015,
            userId = 12,
            fileId = 109,
            fileSHA256 = "iiii9999jjjj0000kkkk1111llll2222mmmm3333nnnn4444",
            fileName = "旅行日记",
            fileExtension = "docx",
            fileCategory = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            fileSize = "65536",
            filePid = 0,
            folderType = 0,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650180,
            lastUpdateTime = 0
        ),
        File(
            id = 1013,
            userId = 12,
            fileId = 107,
            fileSHA256 = "gggg7777hhhh8888iiii9999jjjj0000kkkk1111llll2222",
            fileName = "生日歌",
            fileExtension = "mp3",
            fileCategory = "audio/mpeg",
            fileSize = "262144",
            filePid = 0,
            folderType = 0,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650160,
            lastUpdateTime = 0
        ),
        File(
            id = 1019,
            userId = 12,
            fileId = 113,
            fileSHA256 = "mmmm3333nnnn4444oooo5555pppp6666qqqq7777rrrr8888",
            fileName = "联系人列表",
            fileExtension = "csv",
            fileCategory = "text/csv",
            fileSize = "4096",
            filePid = 0,
            folderType = 0,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650220,
            lastUpdateTime = 0
        ),
        File(
            id = 1014,
            userId = 12,
            fileId = 108,
            fileSHA256 = "hhhh8888iiii9999jjjj0000kkkk1111llll2222mmmm3333",
            fileName = "购物清单",
            fileExtension = "xlsx",
            fileCategory = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            fileSize = "131072",
            filePid = 0,
            folderType = 0,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650170,
            lastUpdateTime = 0
        ),
        File(
            id = 1010,
            userId = 12,
            fileId = 104,
            fileSHA256 = "dddd4444eeee5555ffff6666gggg7777hhhh8888iiii9999",
            fileName = "重要通知",
            fileExtension = "txt",
            fileCategory = "text/plain",
            fileSize = "2097152",
            filePid = 0,
            folderType = 0,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650130,
            lastUpdateTime = 0
        ),
        File(
            id = 1020,
            userId = 12,
            fileId = 114,
            fileSHA256 = "nnnn4444oooo5555pppp6666qqqq7777rrrr8888ssss9999",
            fileName = "项目计划书",
            fileExtension = "pdf",
            fileCategory = "application/pdf",
            fileSize = "2048",
            filePid = 0,
            folderType = 0,
            deleteFlag = 2,
            recoveryTime = 0,
            createTime = 1687650230,
            lastUpdateTime = 0
        )
    )
}